name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Actions for mdbook
      uses: JohnTitor/actions-mdbook@0.1.1
      run: mdbook build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.4
      with:
        build_dir: book
